# Site Settings
title: dot2line | dev blog
email: yands11@gmail.com
description: dot2line's dev blog.
baseurl: ""
url: "https://yands11.github.io/"
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: dot2line
user_description: Android Developer
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: yands11
facebook_username: youngseok.p

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
