title: Warm & Cool
description: >-
  추울 때 따뜻함, 더울 때 시원함처럼 누군가에게 도움이 될 수 있는 글을 적어보는 공간.
author:
  name:	YOUNGSEOK PARK
  email: yands11@gmail.com

theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jemoji

remote-theme: jekyll/minima

google_analytics:	G-295333061

minima:
  skin:	dark
  social_links:
    twitter: dot2line
    github: yands11

