# Site settings
title:       dot2line Blog
author:      dot2line
description: ":rocket: A responsive Jekyll theme based on my personal internet site"
baseurl:     ""
url:         "https://yands11.github.io"

# Social Links
email:            yands11@gmail.com
github_username:  yands11

# Build settings
markdown: kramdown
permalink: pretty
