# Site settings
title:       dot2line Blog
author:      dot2line
description: "dot2line의 Blog : 잡다한 포스팅"
baseurl:     ""
url:         "https://yands11.github.io"

# Social Links
email:            yands11@gmail.com
github_username:  yands11
fb_username:      youngseok.p

# Build settings
markdown: kramdown
permalink: pretty
