baseURL = "https://dot2line.dev/"
languageCode = "en-us"
title = "Neverending coding"
theme = "cactus"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[params]

  description = "About android development"

[[params.social]]
  name = "email"
  link = "yands11@gmail.com" 

[[params.social]]
    name = "github"
    link = "https://github.com/yands11"